# Generated by Django 5.0.3 on 2024-03-13 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('profilephoto', models.ImageField(null=True, upload_to='images/')),
                ('followers', models.IntegerField(default=0, null=True)),
                ('following', models.IntegerField(default=0, null=True)),
                ('no_of_posts', models.IntegerField(default=0, null=True)),
                ('bio', models.CharField(max_length=200, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(max_length=400, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profilepage')),
            ],
        ),
    ]
