# Generated by Django 5.0.3 on 2024-03-14 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_posts_uploader_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Like',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommentOnPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.profilepage')),
            ],
        ),
    ]
