# Generated by Django 4.1.7 on 2024-03-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_posts_like_commentonpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentOnPost',
        ),
    ]
