# Generated by Django 4.1.7 on 2024-03-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_commentonpost_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyOncomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.commentonpost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.profilepage')),
            ],
            options={
                'unique_together': {('user', 'comment', 'time')},
            },
        ),
        migrations.CreateModel(
            name='LikeOnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.commentonpost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.profilepage')),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
