# Generated by Django 5.0.3 on 2024-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_followuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='following',
        ),
        migrations.DeleteModel(
            name='FollowUser',
        ),
        migrations.AddField(
            model_name='profilepage',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower', to='userprofile.profilepage'),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='userprofile.profilepage'),
        ),
    ]
