# Generated by Django 5.0.3 on 2024-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_remove_profilepage_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
