# Generated by Django 5.0.3 on 2024-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_alter_profilepage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='followers',
            field=models.ManyToManyField(blank=True, default=0, related_name='follower', to='userprofile.profilepage'),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='following',
            field=models.ManyToManyField(blank=True, default=0, related_name='following', to='userprofile.profilepage'),
        ),
    ]
