# Generated by Django 5.0.3 on 2024-04-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_alter_profilepage_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
