# Generated by Django 5.0.3 on 2024-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_profilepage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='profilephoto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
