# Generated by Django 5.0.3 on 2024-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_alter_profilepage_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='email',
            field=models.EmailField(max_length=256, null=True, unique=True),
        ),
    ]
