# Generated by Django 5.0.3 on 2024-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_alter_profilepage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
