# Generated by Django 4.1.7 on 2024-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_alter_likepost_user_alter_posts_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
