# Generated by Django 5.0.3 on 2024-05-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_posts_no_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='following',
        ),
        migrations.AddField(
            model_name='profilepage',
            name='no_of_followers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='no_of_following',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
