# Generated by Django 5.0.3 on 2024-05-10 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_followers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentonpost',
            name='like',
        ),
        migrations.AlterField(
            model_name='commentonpost',
            name='description',
            field=models.CharField(default='commented', max_length=400),
        ),
        migrations.AlterField(
            model_name='commentonpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.posts'),
        ),
        migrations.AlterField(
            model_name='commentonpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
