# Generated by Django 5.0.3 on 2024-05-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_remove_commentonpost_like_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replyoncomment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='replyoncomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replyoncomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikeOnComment',
        ),
        migrations.DeleteModel(
            name='ReplyOncomment',
        ),
    ]
